# This file is part of roblesnotes-deploy
# Copyright (C) 2017  Felix Robles Elvira <felrobelv@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
# global non-agora related configuration variables
params:
  # Sometimes services like supervisor take quite a while to restart and some
  # others don't. Configure here exactly how many seconds it should wait for
  # processes that restart slowly or and those that are fast.
  sleep:
    fast: 2
    slow: 15

# global configuration
config:
  domain: roblesnotes.com

  nginx:
    # The folder where the roblesnotes webpage will be generated
    # and the folder nginx will serve
    public_folder: /var/www/html

    # Log level for error log in nginx.
    #
    # This log level stablishes the error_log directive level of error for
    # nginx web server in /etc/nginx/nginx.conf at the http directive. The
    # error log will appear in /var/log/nginx/error.log
    #
    # For more details, see
    # http://nginx.org/en/docs/ngx_core_module.html#error_log
    #
    # Allowed values: debug, info, notice, warn, error, crit, alert, or emerg
    # Default: error
    nginx_error_log_level: error

    # In big elections memory or disk buffer might need to be increased,
    # specifically to upload the list of valid voterids if any filtering is going
    # to be made, or when uploading the list of electors. This setting is
    # applied at once to:
    # play.http.parser.maxDiskBuffer (in agora-elections config)
    # play.http.parser.maxMemoryBuffer (in agora-elections config)
    # parsers.text.maxLength (in agora-elections config)
    # client_max_body_size (in nginx)
    max_body_size: 2m

    # configures the "worker_processes" setting in nginx. Typically you would
    # use the number of cores of the machine or less.
    worker_processes: 1

    # enable/disable nginx reverse proxy cache for everything related to agora
    # web server
    reverse_proxy_cache: true


    # Path of the TLS PEM public certificate.
    #
    # Requirements:
    # - It must be a file with -rw-r--r-- (644) file permissions owned by
    #   agoraelections:users.
    # - Must be a PEM certificate encrypted with the key in the path specified
    #   in config.http.tls_cert_key_path.
    #
    # By default it is '/etc/nginx/cloudflare.pem', but you can change it
    # to any other file you want
    tls_cert_path: /etc/nginx/cloudflare.pem

    # Path of the TLS PEM certificate private key.
    #
    # Requirements:
    # - It must be a file with -rw-r--r-- (644) file permissions owned by
    #   agoraelections:users.
    # - Must be the private key of the public certificate of
    #   config.http.tls_cert_path.
    #
    # By default it is '/etc/nginx/cloudflare.key', but you can
    # change it to any other file you want
    tls_cert_key_path: /etc/nginx/cloudflare.key

    tls_cert: |
           

    tls_cert_key: |
               
